### ISSUE TITLE
Reuse thread pool for threaded tests

### ISSUE THREAD

**Issue by Swatinem** [nvzqz/divan#37]
Being able to run tests multi-threaded simply by adding `DIVAN_THREADS=XXX` to get a feeling for contention is super nice.
However it seems like every benchmark run is using scoped threads under the hood.

Running a threaded benchmark through `samply record`, I end up with well beyond 6k "tracks", each of which is extremely short lived and it is pretty much impossible to select any of the background threads to do proper profiling.

It also appears that a large portion of the main thread time is actually spent creating / destroying threads themselves, at least on macOs where I tested this:

![Bildschirmfoto 2023-12-04 um 11 09 35](https://github.com/nvzqz/divan/assets/580492/dc23aab7-81ac-4395-887b-2fac395a2a77)

**Comment by nvzqz** [comment]
Hey @Swatinem sorry for taking forever on this. As part of Divan's JSON work, I am refactoring Divan's internals and part of that refactor was adding a thread pool. I decided to extract the thread pool out to address your issue, and this fix is now available in `v0.1.16`.
